// Ítems de navegación por rol, TODOS organizados en categorías. En el header, cada categoría es
// un menú desplegable con sus páginas. El único acceso directo es el inicio (Dashboard/Inicio);
// "Cuenta" (perfil) va al menú del usuario, no a la barra.
export const NAV_ITEMS = {
  admin: [
    { key: "dashboard", icon: "dashboard", label: "Dashboard" },
    { key: "empleados", icon: "users", label: "Empleados", group: "Equipo" },
    { key: "usuarios", icon: "userCog", label: "Gestión de Personal", group: "Equipo" },
    { key: "expedientes", icon: "folder", label: "Expedientes", group: "Equipo" },
    { key: "reconocimientos", icon: "award", label: "Reconocimientos", group: "Equipo" },
    { key: "eventospersonal", icon: "cake", label: "Cumpleaños y Aniversarios", group: "Equipo" },
    { key: "asistencia", icon: "clock", label: "Asistencia", group: "Asistencia y rostros" },
    { key: "sucursales", icon: "mapPin", label: "Sucursales", group: "Asistencia y rostros" },
    { key: "horarios", icon: "calendarDays", label: "Horarios", group: "Asistencia y rostros" },
    { key: "importar-horarios", icon: "file", label: "Importar horarios", group: "Asistencia y rostros" },
    { key: "calibracion", icon: "shield", label: "Calibración del cotejo", group: "Asistencia y rostros" },
    { key: "rostros", icon: "camera", label: "Rostros", group: "Asistencia y rostros" },
    { key: "encuestas", icon: "clipboard", label: "Encuestas", group: "Encuestas y reportes" },
    { key: "reportes", icon: "trending", label: "Reportes", group: "Encuestas y reportes" },
    { key: "confidenciales", icon: "lock", label: "Reportes Confidenciales", group: "Encuestas y reportes" },
    { key: "ai", icon: "ai", label: "AI Engine", group: "Herramientas" },
    { key: "config", icon: "settings", label: "Config", group: "Herramientas" },
    { key: "avisos", icon: "bell", label: "Avisos", group: "Herramientas" },
    { key: "soporte", icon: "wrench", label: "Soporte TI", group: "Herramientas" },
    { key: "perfil", icon: "user", label: "Mi perfil", group: "Cuenta" },
  ],
  psicologa: [
    { key: "dashboard", icon: "dashboard", label: "Dashboard" },
    { key: "seguimiento", icon: "target", label: "Seguimiento", group: "Seguimiento" },
    { key: "confidenciales", icon: "lock", label: "Reportes Confidenciales", group: "Seguimiento" },
    { key: "vacaciones", icon: "vacation", label: "Vacaciones", group: "Vacaciones y permisos" },
    { key: "permisos", icon: "clipboardCheck", label: "Permisos", group: "Vacaciones y permisos" },
    { key: "mispermisos", icon: "vacation", label: "Mis vacaciones/permisos", group: "Vacaciones y permisos" },
    { key: "comisiones", icon: "dollar", label: "Comisiones", group: "Vacaciones y permisos" },
    { key: "empleados", icon: "users", label: "Empleados", group: "Equipo" },
    { key: "usuarios", icon: "userCog", label: "Gestión de Personal", group: "Equipo" },
    { key: "expedientes", icon: "folder", label: "Expedientes", group: "Equipo" },
    { key: "reconocimientos", icon: "award", label: "Reconocimientos", group: "Equipo" },
    { key: "eventospersonal", icon: "cake", label: "Cumpleaños y Aniversarios", group: "Equipo" },
    { key: "checador", icon: "clock", label: "Checador", group: "Asistencia y rostros" },
    { key: "asistencia", icon: "clock", label: "Asistencia", group: "Asistencia y rostros" },
    { key: "sucursales", icon: "mapPin", label: "Sucursales", group: "Asistencia y rostros" },
    { key: "horarios", icon: "calendarDays", label: "Horarios", group: "Asistencia y rostros" },
    { key: "importar-horarios", icon: "file", label: "Importar horarios", group: "Asistencia y rostros" },
    { key: "calibracion", icon: "shield", label: "Calibración del cotejo", group: "Asistencia y rostros" },
    { key: "rostros", icon: "camera", label: "Rostros", group: "Asistencia y rostros" },
    { key: "encuestas", icon: "clipboard", label: "Encuestas", group: "Encuestas y reportes" },
    { key: "reportes", icon: "trending", label: "Reportes", group: "Encuestas y reportes" },
    { key: "ai", icon: "ai", label: "AI Engine", group: "Herramientas" },
    { key: "config", icon: "settings", label: "Config", group: "Herramientas" },
    { key: "mensajes", icon: "message", label: "Mensajes", group: "Herramientas" },
    { key: "avisos", icon: "bell", label: "Avisos", group: "Herramientas" },
    { key: "soporte", icon: "wrench", label: "Soporte TI", group: "Herramientas" },
    { key: "perfil", icon: "user", label: "Mi perfil", group: "Cuenta" },
  ],
  rh: [
    { key: "dashboard", icon: "dashboard", label: "Dashboard RH" },
    { key: "usuarios", icon: "userCog", label: "Gestión de Personal", group: "Personal" },
    { key: "empleados", icon: "users", label: "Empleados", group: "Personal" },
    { key: "expedientes", icon: "folder", label: "Expedientes", group: "Personal" },
    { key: "reconocimientos", icon: "award", label: "Reconocimientos", group: "Personal" },
    { key: "eventospersonal", icon: "cake", label: "Cumpleaños y Aniversarios", group: "Personal" },
    { key: "bolsa", icon: "briefcase", label: "Bolsa de trabajo", group: "Personal" },
    { key: "vacaciones", icon: "vacation", label: "Vacaciones", group: "Vacaciones y permisos" },
    { key: "permisos", icon: "clipboardCheck", label: "Permisos", group: "Vacaciones y permisos" },
    { key: "mispermisos", icon: "vacation", label: "Mis vacaciones/permisos", group: "Vacaciones y permisos" },
    { key: "descuentos", icon: "dollar", label: "Descuentos", group: "RH" },
    { key: "comisiones", icon: "dollar", label: "Comisiones", group: "RH" },
    { key: "calendario", icon: "calendar", label: "Calendario", group: "RH" },
    { key: "intercambios", icon: "calendarDays", label: "Intercambios de día", group: "RH" },
    { key: "reportesrh", icon: "trending", label: "Reportes RH", group: "RH" },
    { key: "checador", icon: "clock", label: "Checador", group: "Asistencia y rostros" },
    { key: "asistencia", icon: "clock", label: "Asistencia", group: "Asistencia y rostros" },
    { key: "horarios", icon: "calendarDays", label: "Horarios", group: "Asistencia y rostros" },
    { key: "calibracion", icon: "shield", label: "Calibración del cotejo", group: "Asistencia y rostros" },
    { key: "rostros", icon: "camera", label: "Rostros", group: "Asistencia y rostros" },
    { key: "sucursales", icon: "mapPin", label: "Sucursales", group: "Asistencia y rostros" },
    { key: "encuestas", icon: "clipboard", label: "Encuestas", group: "Encuestas y reportes" },
    { key: "reportes", icon: "trending", label: "Reportes", group: "Encuestas y reportes" },
    { key: "ai", icon: "ai", label: "AI Engine", group: "Herramientas" },
    { key: "config", icon: "settings", label: "Config", group: "Herramientas" },
    { key: "avisos", icon: "bell", label: "Avisos", group: "Herramientas" },
    { key: "soporte", icon: "wrench", label: "Soporte TI", group: "Herramientas" },
    { key: "perfil", icon: "user", label: "Mi perfil", group: "Cuenta" },
  ],
  empleado: [
    { key: "inicio", icon: "home", label: "Inicio" },
    { key: "checador", icon: "clock", label: "Checador", group: "Mi trabajo" },
    { key: "encuesta", icon: "clipboardCheck", label: "Mi Encuesta", group: "Mi trabajo" },
    { key: "historial", icon: "history", label: "Historial", group: "Mi trabajo" },
    { key: "rostro", icon: "camera", label: "Mi rostro", group: "Mi trabajo" },
    { key: "permisosempleado", icon: "vacation", label: "Vacaciones", group: "Mi trabajo" },
    { key: "calendario", icon: "calendar", label: "Calendario", group: "Mi trabajo" },
    { key: "reconocimientos", icon: "award", label: "Reconocimientos", group: "Mi trabajo" },
    { key: "reporteconfidencial", icon: "lock", label: "Reporte Confidencial", group: "Mi trabajo" },
    { key: "mensajes", icon: "message", label: "Mensajes", group: "Herramientas" },
    { key: "avisos", icon: "bell", label: "Avisos", group: "Herramientas" },
    { key: "soporte", icon: "wrench", label: "Soporte TI", group: "Herramientas" },
    { key: "perfil", icon: "user", label: "Mi perfil", group: "Cuenta" },
  ],
  doctor: [
    { key: "inicio", icon: "home", label: "Inicio" },
    { key: "comisiones", icon: "dollar", label: "Comisiones", group: "Mi trabajo" },
    { key: "checador", icon: "clock", label: "Checador", group: "Mi trabajo" },
    { key: "encuesta", icon: "clipboardCheck", label: "Mi Encuesta", group: "Mi trabajo" },
    { key: "historial", icon: "history", label: "Historial", group: "Mi trabajo" },
    { key: "rostro", icon: "camera", label: "Mi rostro", group: "Mi trabajo" },
    { key: "permisosempleado", icon: "vacation", label: "Vacaciones", group: "Mi trabajo" },
    { key: "calendario", icon: "calendar", label: "Calendario", group: "Mi trabajo" },
    { key: "reconocimientos", icon: "award", label: "Reconocimientos", group: "Mi trabajo" },
    { key: "reporteconfidencial", icon: "lock", label: "Reporte Confidencial", group: "Mi trabajo" },
    { key: "mensajes", icon: "message", label: "Mensajes", group: "Herramientas" },
    { key: "avisos", icon: "bell", label: "Avisos", group: "Herramientas" },
    { key: "soporte", icon: "wrench", label: "Soporte TI", group: "Herramientas" },
    { key: "perfil", icon: "user", label: "Mi perfil", group: "Cuenta" },
  ],
};

// Agrupa una lista de ítems por su campo `group`, preservando el orden de aparición del grupo.
export const agruparPorCampo = (lista) => {
  const grupos = [];
  const indice = new Map();
  for (const item of lista) {
    const g = item.group || null;
    if (!indice.has(g)) { indice.set(g, grupos.length); grupos.push({ nombre: g, items: [] }); }
    grupos[indice.get(g)].items.push(item);
  }
  return grupos;
};
