import {
  LayoutDashboard,
  Bot,
  Search,
  Users,
  Settings,
  FolderOpen,
  Award,
  Cake,
  ClipboardList,
  TrendingUp,
  Lock,
  Home,
  FileText,
  History,
  Palmtree,
  MessageSquare,
  Target,
  Calendar,
  DollarSign,
  BarChart3,
  Sparkles,
  User,
  Heart,
  Pin,
  Paperclip,
  Shield,
  Bell,
  AlertTriangle,
  Gift,
  Clock,
  Plus,
  FileSpreadsheet,
  Building2,
  CheckCircle2,
  Circle,
  Key,
  LogOut,
  Activity,
  Brain,
  FileBarChart,
  UserCog,
  CalendarDays,
  ClipboardCheck,
  ShieldAlert,
  Inbox,
  CircleDot,
  Minus,
  XCircle,
  Star,
  StickyNote,
  Wand2,
  FolderSearch,
  Lightbulb,
  Wrench,
  TrendingDown,
  Eye,
  Sun,
  Moon,
  Briefcase,
  Camera,
  MapPin,
} from "lucide-react";

const ICON_MAP = {
  dashboard: LayoutDashboard,
  ai: Bot,
  users: Users,
  settings: Settings,
  folder: FolderOpen,
  award: Award,
  cake: Cake,
  clipboard: ClipboardList,
  trending: TrendingUp,
  lock: Lock,
  home: Home,
  file: FileText,
  history: History,
  vacation: Palmtree,
  message: MessageSquare,
  target: Target,
  calendar: Calendar,
  dollar: DollarSign,
  chart: BarChart3,
  sparkles: Sparkles,
  user: User,
  heart: Heart,
  pin: Pin,
  paperclip: Paperclip,
  shield: Shield,
  bell: Bell,
  alert: AlertTriangle,
  gift: Gift,
  clock: Clock,
  plus: Plus,
  spreadsheet: FileSpreadsheet,
  building: Building2,
  check: CheckCircle2,
  circle: Circle,
  key: Key,
  logout: LogOut,
  activity: Activity,
  brain: Brain,
  report: FileBarChart,
  userCog: UserCog,
  calendarDays: CalendarDays,
  clipboardCheck: ClipboardCheck,
  shieldAlert: ShieldAlert,
  inbox: Inbox,
  stable: CircleDot,
  warning: AlertTriangle,
  critical: Circle,
  minus: Minus,
  search: Search,
  party: Gift,
  xCircle: XCircle,
  star: Star,
  note: StickyNote,
  wand: Wand2,
  folderSearch: FolderSearch,
  lightbulb: Lightbulb,
  wrench: Wrench,
  trendingDown: TrendingDown,
  eye: Eye,
  sun: Sun,
  moon: Moon,
  briefcase: Briefcase,
  camera: Camera,
  mapPin: MapPin,
};

const Icon = ({ name, size = 18, className = "", strokeWidth = 1.75, color }) => {
  const LucideIcon = ICON_MAP[name];
  if (!LucideIcon) return null;
  return (
    <LucideIcon
      size={size}
      className={`mc-icon ${className}`.trim()}
      strokeWidth={strokeWidth}
      color={color}
      aria-hidden="true"
    />
  );
};

export default Icon;
